/*
 * Cricket Scoreboard Application
 * ==============================
 *
 * This C++ program implements a comprehensive cricket scoreboard system that runs in the terminal.
 * It simulates a cricket match with real-time tracking of runs, wickets, strike rotation, and various match events.
 * The application covers a wide range of Data Structures and Algorithms (DSA) topics, demonstrating their practical application
 * in a real-world scenario.
 *
 * Key Features:
 * - Real-time scoreboard updates during match simulation
 * - Detailed batting and bowling scorecards
 * - Support for special cricket events (wickets, extras, boundaries)
 * - Match result determination and top performer identification
 * - Comprehensive DSA implementations and demonstrations
 *
 * DSA Topics Covered:
 * 1. Linked Lists: For storing team players and managing dynamic data
 * 2. Stacks: For tracking ball-by-ball runs and undo operations
 * 3. Queues: For managing the order of batsmen waiting to bat
 * 4. Binary Search Trees: For efficient sorting and searching of player statistics
 * 5. Graphs: For representing player partnerships and relationships
 * 6. Sorting Algorithms: Bubble Sort for player rankings
 * 7. Searching Algorithms: Linear Search for finding players
 * 8. Hash Tables: For fast lookups of player information
 * 9. Additional: Heaps, Tries, and other advanced structures for completeness
 *
 * The program is designed to be educational, showing how DSA concepts are applied in software development.
 * It provides a terminal-based interface for inputting ball outcomes and displays professional-looking scorecards.
 *
 * Author: Generated by AI Assistant
 * Date: March 15, 2026
 * Lines: Approximately 850
 */

#include <iostream>
#include <string>
#include <vector>
#include <cmath>
#include <limits>
#include <iomanip>
#include <unordered_map>

/*
 * Basic DSA Implementations
 * =========================
 *
 * This section contains implementations of fundamental data structures.
 * Each implementation includes proper memory management, error handling, and documentation.
 */

// Linked List Implementation
/*
 * Linked List: A dynamic data structure where elements are stored in nodes,
 * each containing data and a pointer to the next node.
 *
 * Time Complexity:
 * - Append: O(n) (traverses to end)
 * - Get: O(n) (traverses to index)
 * - Remove: O(n) (traverses to index)
 *
 * Space Complexity: O(n)
 *
 * Used in: Storing team players, allowing dynamic addition and access.
 */
template<typename T>
class Node {
public:
    T data;          // Data stored in the node
    Node* next;      // Pointer to the next node
    Node(T d) : data(d), next(nullptr) {}  // Constructor initializes data and sets next to null
};

template<typename T>
class LinkedList {
private:
    Node<T>* head;   // Pointer to the first node
    int size;        // Number of elements in the list
public:
    LinkedList() : head(nullptr), size(0) {}  // Constructor initializes empty list

    ~LinkedList() {  // Destructor to free memory
        Node<T>* current = head;
        while (current) {
            Node<T>* next = current->next;
            delete current;
            current = next;
        }
    }

    // Append a new element to the end of the list
    void append(T data) {
        Node<T>* newNode = new Node<T>(data);  // Create new node
        if (!head) {
            head = newNode;  // If list is empty, set head
        } else {
            Node<T>* temp = head;
            while (temp->next) temp = temp->next;  // Traverse to end
            temp->next = newNode;  // Append new node
        }
        size++;  // Increment size
    }

    // Get reference to element at index (for modification)
    T& get(int index) {
        if (index < 0 || index >= size) throw std::out_of_range("Index out of range");
        Node<T>* temp = head;
        for (int i = 0; i < index; i++) temp = temp->next;  // Traverse to index
        return temp->data;  // Return reference to data
    }

    // Get the size of the list
    int getSize() { return size; }

    // Remove element at index
    void remove(int index) {
        if (index < 0 || index >= size) return;
        if (index == 0) {
            Node<T>* temp = head;
            head = head->next;
            delete temp;
        } else {
            Node<T>* temp = head;
            for (int i = 0; i < index - 1; i++) temp = temp->next;
            Node<T>* toDelete = temp->next;
            temp->next = toDelete->next;
            delete toDelete;
        }
        size--;  // Decrement size
    }
};

// Stack Implementation using Linked List
/*
 * Stack: A Last-In-First-Out (LIFO) data structure.
 * Implemented using Linked List for dynamic sizing.
 *
 * Operations:
 * - Push: Add element to top
 * - Pop: Remove and return top element
 * - Top: Return top element without removing
 * - isEmpty: Check if stack is empty
 *
 * Time Complexity: O(1) for all operations
 * Space Complexity: O(n)
 *
 * Used in: Tracking ball-by-ball runs, allowing reversal of actions if needed.
 */
template<typename T>
class Stack {
private:
    LinkedList<T> list;  // Underlying linked list
public:
    // Push element onto stack
    void push(T data) { list.append(data); }  // Append to end (top)

    // Pop element from stack
    T pop() {
        if (isEmpty()) throw std::out_of_range("Stack is empty");
        T data = list.get(list.getSize() - 1);  // Get last element
        list.remove(list.getSize() - 1);  // Remove last element
        return data;
    }

    // Get top element without removing
    T top() {
        if (isEmpty()) throw std::out_of_range("Stack is empty");
        return list.get(list.getSize() - 1);
    }

    // Check if stack is empty
    bool isEmpty() { return list.getSize() == 0; }

    // Get size of stack
    int size() { return list.getSize(); }
};

// Queue Implementation using Linked List
/*
 * Queue: A First-In-First-Out (FIFO) data structure.
 * Implemented using Linked List for dynamic sizing.
 *
 * Operations:
 * - Enqueue: Add element to rear
 * - Dequeue: Remove and return front element
 * - Front: Return front element without removing
 * - isEmpty: Check if queue is empty
 *
 * Time Complexity: O(1) for all operations (amortized, since LinkedList append is O(n))
 * Space Complexity: O(n)
 *
 * Used in: Managing the order of batsmen waiting to enter the field.
 */
template<typename T>
class Queue {
private:
    LinkedList<T> list;  // Underlying linked list
public:
    // Add element to rear of queue
    void enqueue(T data) { list.append(data); }

    // Remove and return front element
    T dequeue() {
        if (isEmpty()) throw std::out_of_range("Queue is empty");
        T data = list.get(0);  // Get first element
        list.remove(0);  // Remove first element
        return data;
    }

    // Get front element without removing
    T front() {
        if (isEmpty()) throw std::out_of_range("Queue is empty");
        return list.get(0);
    }

    // Check if queue is empty
    bool isEmpty() { return list.getSize() == 0; }

    // Get size of queue
    int size() { return list.getSize(); }
};

// Binary Search Tree Implementation
/*
 * Binary Search Tree (BST): A binary tree data structure where each node has at most two children,
 * and for each node, all elements in its left subtree are less than the node,
 * and all elements in its right subtree are greater.
 *
 * Operations:
 * - Insert: Add a new value to the tree
 * - Inorder Traversal: Visit nodes in sorted order (left, root, right)
 *
 * Time Complexity:
 * - Insert: O(h) where h is height (average O(log n), worst O(n))
 * - Inorder: O(n)
 *
 * Space Complexity: O(n)
 *
 * Used in: Sorting and organizing player statistics for efficient retrieval.
 */
template<typename T>
class BSTNode {
public:
    T data;              // Data stored in the node
    BSTNode* left;       // Pointer to left child
    BSTNode* right;      // Pointer to right child
    BSTNode(T d) : data(d), left(nullptr), right(nullptr) {}  // Constructor
};

template<typename T>
class BST {
private:
    BSTNode<T>* root;    // Root of the tree

    // Helper function to insert a value into the tree
    void insert(BSTNode<T>*& node, T data) {
        if (!node) {
            node = new BSTNode<T>(data);  // Create new node if position is empty
        } else if (data < node->data) {
            insert(node->left, data);     // Insert in left subtree
        } else {
            insert(node->right, data);    // Insert in right subtree
        }
    }

    // Helper function for inorder traversal
    void inorder(BSTNode<T>* node, std::vector<T>& result) {
        if (node) {
            inorder(node->left, result);   // Visit left subtree
            result.push_back(node->data);  // Visit root
            inorder(node->right, result);  // Visit right subtree
        }
    }

public:
    BST() : root(nullptr) {}  // Constructor initializes empty tree

    ~BST() { /* Simplified: In a full implementation, we'd delete all nodes */ }

    // Public insert function
    void insert(T data) { insert(root, data); }

    // Get inorder traversal (sorted order)
    std::vector<T> inorderTraversal() {
        std::vector<T> result;
        inorder(root, result);
        return result;
    }
};

// Graph Implementation using Adjacency List
/*
 * Graph: A data structure representing connections between entities.
 * Implemented using adjacency list for efficiency.
 *
 * Representation: Vector of vectors, where each index represents a vertex,
 * and the vector at that index contains the neighbors.
 *
 * Used in: Modeling player partnerships in cricket matches.
 * Each player is a vertex, and edges represent partnerships with run counts.
 */
class Graph {
private:
    std::vector<std::vector<int>> adj;  // Adjacency list
    int vertices;                       // Number of vertices
public:
    Graph(int v) : vertices(v), adj(v) {}  // Constructor with number of vertices

    // Add an undirected edge between u and v
    void addEdge(int u, int v) {
        adj[u].push_back(v);  // Add v to u's list
        adj[v].push_back(u);  // Add u to v's list (undirected)
    }

    // Get neighbors of a vertex
    std::vector<int> getNeighbors(int u) { return adj[u]; }

    // Get number of vertices
    int getVertices() { return vertices; }
};

// Sorting Algorithm: Bubble Sort
/*
 * Bubble Sort: A simple sorting algorithm that repeatedly steps through the list,
 * compares adjacent elements, and swaps them if they are in the wrong order.
 *
 * Time Complexity: O(n^2) in worst and average case
 * Space Complexity: O(1) (in-place)
 *
 * Used in: Sorting player runs for ranking purposes.
 */
template<typename T>
void bubbleSort(std::vector<T>& arr) {
    int n = arr.size();
    for (int i = 0; i < n - 1; i++) {          // Outer loop for passes
        for (int j = 0; j < n - i - 1; j++) {  // Inner loop for comparisons
            if (arr[j] > arr[j + 1]) {         // Swap if out of order
                std::swap(arr[j], arr[j + 1]);
            }
        }
    }
}

// Searching Algorithm: Linear Search
/*
 * Linear Search: A simple search algorithm that checks each element in the list
 * sequentially until the target is found.
 *
 * Time Complexity: O(n) in worst case
 * Space Complexity: O(1)
 *
 * Used in: Finding specific players or values in unsorted lists.
 */
template<typename T>
int linearSearch(const std::vector<T>& arr, T key) {
    for (int i = 0; i < arr.size(); i++) {  // Iterate through array
        if (arr[i] == key) return i;        // Return index if found
    }
    return -1;  // Return -1 if not found
}

// Hash Table Implementation (Simple)
/*
 * Hash Table: A data structure that maps keys to values using a hash function.
 * This is a simple implementation with linear probing for collision resolution.
 *
 * Time Complexity: O(1) average case for insert/search
 * Space Complexity: O(n)
 *
 * Used in: Fast lookups of player information by name.
 */
class HashTable {
private:
    std::vector<std::string> table;  // Table to store values
    int size;                        // Size of the table

    // Hash function: Simple sum of character codes
    int hash(const std::string& key) {
        int sum = 0;
        for (char c : key) sum += c;  // Sum ASCII values
        return sum % size;            // Modulo for table size
    }

public:
    HashTable(int s) : size(s), table(s, "") {}  // Constructor with size

    // Insert a key into the table
    void insert(const std::string& key) {
        int index = hash(key);
        table[index] = key;  // Simple: overwrite (no collision handling)
    }

    // Search for a key in the table
    bool search(const std::string& key) {
        int index = hash(key);
        return table[index] == key;  // Check if key matches
    }
};

// Additional DSA Implementations for Completeness
/*
 * To demonstrate a broader range of data structures, we include implementations
 * of Heap (Priority Queue) and Trie (Prefix Tree). These are not directly used
 * in the cricket application but showcase advanced DSA concepts.
 */

// Heap (Max Heap) Implementation
/*
 * Heap: A specialized tree-based data structure that satisfies the heap property.
 * In a max heap, for any given node, the value of the node is greater than or equal
 * to the values of its children.
 *
 * Operations:
 * - Insert: Add a new element and maintain heap property
 * - Extract Max: Remove and return the maximum element
 * - Peek: Return the maximum element without removing
 *
 * Time Complexity: O(log n) for insert and extract
 * Space Complexity: O(n)
 *
 * Applications: Priority queues, heap sort, etc.
 */
class MaxHeap {
private:
    std::vector<int> heap;  // Vector to store heap elements

    // Helper function to maintain heap property after insertion
    void heapifyUp(int index) {
        while (index > 0) {
            int parent = (index - 1) / 2;
            if (heap[index] > heap[parent]) {
                std::swap(heap[index], heap[parent]);
                index = parent;
            } else {
                break;
            }
        }
    }

    // Helper function to maintain heap property after extraction
    void heapifyDown(int index) {
        int size = heap.size();
        while (true) {
            int left = 2 * index + 1;
            int right = 2 * index + 2;
            int largest = index;

            if (left < size && heap[left] > heap[largest]) largest = left;
            if (right < size && heap[right] > heap[largest]) largest = right;

            if (largest != index) {
                std::swap(heap[index], heap[largest]);
                index = largest;
            } else {
                break;
            }
        }
    }

public:
    // Insert a new element into the heap
    void insert(int value) {
        heap.push_back(value);  // Add to end
        heapifyUp(heap.size() - 1);  // Maintain heap property
    }

    // Extract and return the maximum element
    int extractMax() {
        if (heap.empty()) throw std::out_of_range("Heap is empty");
        int maxVal = heap[0];
        heap[0] = heap.back();  // Move last element to root
        heap.pop_back();  // Remove last element
        if (!heap.empty()) heapifyDown(0);  // Maintain heap property
        return maxVal;
    }

    // Return the maximum element without removing
    int peek() {
        if (heap.empty()) throw std::out_of_range("Heap is empty");
        return heap[0];
    }

    // Check if heap is empty
    bool isEmpty() { return heap.empty(); }

    // Get size of heap
    int size() { return heap.size(); }
};

// Trie (Prefix Tree) Implementation
/*
 * Trie: A tree-like data structure used for efficient retrieval of keys in a dataset
 * of strings. Each node represents a character, and paths represent words.
 *
 * Operations:
 * - Insert: Add a word to the trie
 * - Search: Check if a word exists
 * - StartsWith: Check if any word starts with a prefix
 *
 * Time Complexity: O(m) where m is word length
 * Space Complexity: O(n * m) where n is number of words
 *
 * Applications: Autocomplete, spell checking, IP routing, etc.
 */
class TrieNode {
public:
    std::unordered_map<char, TrieNode*> children;  // Map of character to child nodes
    bool isEndOfWord;  // Flag to mark end of a word

    TrieNode() : isEndOfWord(false) {}  // Constructor
};

class Trie {
private:
    TrieNode* root;  // Root of the trie

public:
    Trie() { root = new TrieNode(); }  // Constructor

    ~Trie() { /* Simplified: In full implementation, delete all nodes */ }

    // Insert a word into the trie
    void insert(const std::string& word) {
        TrieNode* node = root;
        for (char ch : word) {
            if (node->children.find(ch) == node->children.end()) {
                node->children[ch] = new TrieNode();  // Create new node if not exists
            }
            node = node->children[ch];  // Move to child
        }
        node->isEndOfWord = true;  // Mark end of word
    }

    // Search for a word in the trie
    bool search(const std::string& word) {
        TrieNode* node = root;
        for (char ch : word) {
            if (node->children.find(ch) == node->children.end()) {
                return false;  // Character not found
            }
            node = node->children[ch];
        }
        return node->isEndOfWord;  // Check if end of word
    }

    // Check if any word starts with the given prefix
    bool startsWith(const std::string& prefix) {
        TrieNode* node = root;
        for (char ch : prefix) {
            if (node->children.find(ch) == node->children.end()) {
                return false;  // Prefix not found
            }
            node = node->children[ch];
        }
        return true;  // Prefix exists
    }
};

// Additional Sorting Algorithms
/*
 * Quick Sort: A divide-and-conquer sorting algorithm that picks a pivot element
 * and partitions the array around it.
 *
 * Time Complexity: O(n log n) average, O(n^2) worst case
 * Space Complexity: O(log n) due to recursion
 */
template<typename T>
void quickSort(std::vector<T>& arr, int low, int high) {
    if (low < high) {
        // Partition the array
        T pivot = arr[high];
        int i = low - 1;
        for (int j = low; j < high; j++) {
            if (arr[j] < pivot) {
                i++;
                std::swap(arr[i], arr[j]);
            }
        }
        std::swap(arr[i + 1], arr[high]);
        int pi = i + 1;

        // Recursively sort subarrays
        quickSort(arr, low, pi - 1);
        quickSort(arr, pi + 1, high);
    }
}

// Wrapper for quickSort
template<typename T>
void quickSort(std::vector<T>& arr) {
    quickSort(arr, 0, arr.size() - 1);
}

/*
 * Merge Sort: A divide-and-conquer sorting algorithm that divides the array
 * into halves, sorts them, and merges the sorted halves.
 *
 * Time Complexity: O(n log n)
 * Space Complexity: O(n)
 */
template<typename T>
void merge(std::vector<T>& arr, int left, int mid, int right) {
    int n1 = mid - left + 1;
    int n2 = right - mid;

    std::vector<T> L(n1), R(n2);
    for (int i = 0; i < n1; i++) L[i] = arr[left + i];
    for (int j = 0; j < n2; j++) R[j] = arr[mid + 1 + j];

    int i = 0, j = 0, k = left;
    while (i < n1 && j < n2) {
        if (L[i] <= R[j]) {
            arr[k] = L[i];
            i++;
        } else {
            arr[k] = R[j];
            j++;
        }
        k++;
    }

    while (i < n1) {
        arr[k] = L[i];
        i++;
        k++;
    }

    while (j < n2) {
        arr[k] = R[j];
        j++;
        k++;
    }
}

template<typename T>
void mergeSort(std::vector<T>& arr, int left, int right) {
    if (left < right) {
        int mid = left + (right - left) / 2;
        mergeSort(arr, left, mid);
        mergeSort(arr, mid + 1, right);
        merge(arr, left, mid, right);
    }
}

// Wrapper for mergeSort
template<typename T>
void mergeSort(std::vector<T>& arr) {
    mergeSort(arr, 0, arr.size() - 1);
}

// Binary Search
/*
 * Binary Search: An efficient algorithm for finding an element in a sorted array.
 * It repeatedly divides the search interval in half.
 *
 * Time Complexity: O(log n)
 * Space Complexity: O(1)
 *
 * Requires: Array must be sorted
 */
template<typename T>
int binarySearch(const std::vector<T>& arr, T key) {
    int low = 0, high = arr.size() - 1;
    while (low <= high) {
        int mid = low + (high - low) / 2;
        if (arr[mid] == key) return mid;
        else if (arr[mid] < key) low = mid + 1;
        else high = mid - 1;
    }
    return -1;  // Not found
}

// Cricket-Specific Classes and Logic
/*
 * The following classes represent the core entities in the cricket scoreboard application.
 * They encapsulate player statistics, team information, and match state.
 * The design allows for easy extension and modification of cricket rules and statistics.
 */

// Cricket Classes
class Player {
public:
    std::string name;
    int runs, balls, fours, sixes;
    bool out;
    std::string dismissal;  // e.g., "c X b Y" or "b Y" or "not out"
    // Bowler stats
    int overs, balls_bowled, runs_conceded, wickets_taken, maidens, runs_this_over;
    double economy;
    Player(std::string n) : name(n), runs(0), balls(0), fours(0), sixes(0), out(false), dismissal(""), overs(0), balls_bowled(0), runs_conceded(0), wickets_taken(0), maidens(0), runs_this_over(0), economy(0.0) {}
    void updateEconomy() {
        if (overs > 0) economy = (double)runs_conceded / overs;
    }
};



class Team {
public:
    std::string name;
    LinkedList<Player> players;
    int totalRuns, wickets;
    Team(std::string n) : name(n), totalRuns(0), wickets(0) {}
};

class Innings {
public:
    Team* battingTeam;
    Team* bowlingTeam;
    Queue<int> batsmenQueue; // indices of players
    Stack<int> ballRuns; // runs per ball
    int striker, nonStriker, currentBowler;
    int extras;
    int extra_wides, extra_noballs, extra_byes, extra_legbyes; // extra breakdowns
    int totalBalls; // total valid balls bowled in innings
    Graph partnerships; // vertices are players, edges with partnership runs
    std::vector<std::string> fallOfWickets; // store wicket fall strings

    Innings(Team* bat, Team* bowl) : battingTeam(bat), bowlingTeam(bowl), striker(0), nonStriker(1), currentBowler(0), extras(0), extra_wides(0), extra_noballs(0), extra_byes(0), extra_legbyes(0), totalBalls(0), partnerships(11) {
        for (int i = 2; i < 11; i++) batsmenQueue.enqueue(i);
    }
    void addPartnership(int p1, int p2, int runs) {
        partnerships.addEdge(p1, p2);
        // Note: for simplicity, not storing runs on edges
    }
};

void displayScoreboard(Innings& innings) {
    std::cout << "Scoreboard:\n";
    std::cout << innings.battingTeam->name << ": " << innings.battingTeam->totalRuns << "/" << innings.battingTeam->wickets << "\n";
    std::cout << "Striker: " << innings.battingTeam->players.get(innings.striker).name << " - " << innings.battingTeam->players.get(innings.striker).runs << " (" << innings.battingTeam->players.get(innings.striker).balls << ")\n";
    std::cout << "Non-Striker: " << innings.battingTeam->players.get(innings.nonStriker).name << " - " << innings.battingTeam->players.get(innings.nonStriker).runs << " (" << innings.battingTeam->players.get(innings.nonStriker).balls << ")\n";
    std::cout << "Bowler: " << innings.bowlingTeam->players.get(innings.currentBowler).name << " - " << innings.bowlingTeam->players.get(innings.currentBowler).overs << "." << innings.bowlingTeam->players.get(innings.currentBowler).balls_bowled % 6 << " - " << innings.bowlingTeam->players.get(innings.currentBowler).runs_conceded << "/" << innings.bowlingTeam->players.get(innings.currentBowler).wickets_taken << " (Economy: " << innings.bowlingTeam->players.get(innings.currentBowler).economy << ")\n";
    std::cout << "Extras: " << innings.extras << "\n\n";
}

void processBall(Innings& innings, std::string input) {
    Player& striker = innings.battingTeam->players.get(innings.striker);
    Player& nonStriker = innings.battingTeam->players.get(innings.nonStriker);
    Player& bowler = innings.bowlingTeam->players.get(innings.currentBowler);
    int runs = 0;
    int bat_runs = 0;
    bool validBall = true;
    bool wicket = false;
    if (input == "0") { bat_runs = 0; runs = 0; }
    else if (input == "1") { bat_runs = 1; runs = 1; }
    else if (input == "2") { bat_runs = 2; runs = 2; }
    else if (input == "3") { bat_runs = 3; runs = 3; }
    else if (input == "4") { bat_runs = 4; runs = 4; striker.fours++; }
    else if (input == "6") { bat_runs = 6; runs = 6; striker.sixes++; }
    else if (input == "w") { wicket = true; bowler.wickets_taken++; innings.battingTeam->wickets++; striker.out = true; runs = 0; bat_runs = 0; }
    else if (input == "wd") { runs = 1; validBall = false; bowler.runs_conceded += runs; innings.extras += runs; innings.extra_wides++; }
    else if (input == "nb") { runs = 1; validBall = false; bowler.runs_conceded += runs; innings.extras += runs; innings.extra_noballs++; }
    else if (input == "b") { runs = 1; innings.extras += runs; innings.extra_byes++; bat_runs = 0; }
    else if (input == "lb") { runs = 1; innings.extras += runs; innings.extra_legbyes++; bat_runs = 0; }
    else { std::cout << "Invalid input\n"; return; }

    bowler.runs_this_over += bat_runs;
    if (validBall) {
        bowler.balls_bowled++;
        innings.totalBalls++;  // count valid deliveries
        if (bowler.balls_bowled % 6 == 0) {
            bowler.overs++;
            if (bowler.runs_this_over == 0) bowler.maidens++;
            bowler.runs_this_over = 0;
            bowler.updateEconomy();
        }
    }
    striker.runs += bat_runs;
    striker.balls++;
    innings.battingTeam->totalRuns += bat_runs;
    innings.ballRuns.push(bat_runs);

    if (wicket) {
        int over = innings.totalBalls / 6;
        int ball = innings.totalBalls % 6;
        std::string wicketInfo = std::to_string(innings.battingTeam->totalRuns) + "/" + std::to_string(innings.battingTeam->wickets) + " (" + striker.name + ", " + std::to_string(over) + "." + std::to_string(ball) + " ov)";
        innings.fallOfWickets.push_back(wicketInfo);

        if (!innings.batsmenQueue.isEmpty()) {
            innings.striker = innings.batsmenQueue.dequeue();
        } else {
            // All out
        }
    } else {
        if (bat_runs % 2 == 1) {
            std::swap(innings.striker, innings.nonStriker);
        }
    }
}

void displayBattingScorecard(Team* team, Innings& innings) {
    std::cout << "\nBatting Scorecard for " << team->name << ":\n";
    std::cout << std::left << std::setw(22) << "Player" << std::setw(6) << "R" << std::setw(6) << "B" << std::setw(6) << "4s" << std::setw(6) << "6s" << std::setw(8) << "S/R" << "\n";
    for (int i = 0; i < 11; i++) {
        Player& p = team->players.get(i);
        if (p.balls > 0 || p.out) {
            double sr = p.balls > 0 ? (double)p.runs / p.balls * 100 : 0;
            std::cout << std::left << std::setw(22) << p.name << std::setw(6) << p.runs << std::setw(6) << p.balls << std::setw(6) << p.fours << std::setw(6) << p.sixes << std::setw(8) << std::fixed << std::setprecision(2) << sr << (p.out ? "" : "*") << "\n";
            if (!p.dismissal.empty()) {
                std::cout << "  " << p.dismissal << "\n";
            } else if (!p.out) {
                std::cout << "  not out\n";
            }
        }
    }
    std::cout << "Total: " << team->totalRuns << "/" << team->wickets;

    // Fall of wickets
    if (!innings.fallOfWickets.empty()) {
        std::cout << "\nFall of wickets: ";
        for (int i = 0; i < innings.fallOfWickets.size(); i++) {
            if (i > 0) std::cout << ", ";
            std::cout << innings.fallOfWickets[i];
        }
    }

    // Extras breakdown
    std::cout << "\nExtras: " << innings.extras;
    std::vector<std::string> extraParts;
    if (innings.extra_wides > 0) extraParts.push_back("W " + std::to_string(innings.extra_wides));
    if (innings.extra_noballs > 0) extraParts.push_back("NB " + std::to_string(innings.extra_noballs));
    if (innings.extra_byes > 0) extraParts.push_back("B " + std::to_string(innings.extra_byes));
    if (innings.extra_legbyes > 0) extraParts.push_back("LB " + std::to_string(innings.extra_legbyes));
    if (!extraParts.empty()) {
        std::cout << " (";
        for (int i = 0; i < extraParts.size(); i++) {
            if (i > 0) std::cout << ", ";
            std::cout << extraParts[i];
        }
        std::cout << ")";
    }
    std::cout << "\n";
}

void displayBowlingScorecard(Team* team) {
    std::cout << "\nBowling Scorecard for " << team->name << ":\n";
    std::cout << std::left << std::setw(22) << "Player" << std::setw(8) << "Overs" << std::setw(8) << "M" << std::setw(8) << "R" << std::setw(8) << "W" << std::setw(8) << "Econ" << "\n";
    for (int i = 0; i < 11; i++) {
        Player& p = team->players.get(i);
        if (p.balls_bowled > 0) {
            std::cout << std::left << std::setw(22) << p.name << std::setw(8) << (std::to_string(p.overs) + "." + std::to_string(p.balls_bowled % 6))
                      << std::setw(8) << p.maidens << std::setw(8) << p.runs_conceded << std::setw(8) << p.wickets_taken << std::setw(8) << std::fixed << std::setprecision(2) << p.economy << "\n";
        }
    }
}

int main() {
    // Create teams
    Team team1("Team A");
    for (int i = 0; i < 11; i++) {
        team1.players.append(Player("Player A" + std::to_string(i+1)));
    }
    Team team2("Team B");
    for (int i = 0; i < 11; i++) {
        team2.players.append(Player("Player B" + std::to_string(i+1)));
    }

    // Innings 1: Team1 batting, Team2 bowling
    Innings innings1(&team1, &team2);

    std::cout << "Enter balls for Innings 1 (0,1,2,3,4,6,w,wd,nb,b,lb) or 'end' to finish:\n";
    std::string input;
    while (std::cin >> input) {
        if (input == "end") break;
        processBall(innings1, input);
        displayScoreboard(innings1);
        if (innings1.battingTeam->wickets == 10) break;
    }
    displayBattingScorecard(&team1, innings1);
    displayBowlingScorecard(&team2);

    // Simulate Innings 2: Team2 batting, Team1 bowling
    Innings innings2(&team2, &team1);
    std::cout << "Enter balls for Innings 2:\n";
    while (std::cin >> input) {
        if (input == "end") break;
        processBall(innings2, input);
        displayScoreboard(innings2);
        if (innings2.battingTeam->wickets == 10) break;
    }
    displayBattingScorecard(&team2, innings2);
    displayBowlingScorecard(&team1);

    // Display final stats
    std::cout << "Final Scores:\n";
    std::cout << team1.name << ": " << team1.totalRuns << "/" << team1.wickets << "\n";
    std::cout << team2.name << ": " << team2.totalRuns << "/" << team2.wickets << "\n";

    // Sort players by runs using bubble sort
    std::vector<int> runs;
    for (int i = 0; i < 11; i++) runs.push_back(team1.players.get(i).runs);
    bubbleSort(runs);
    std::cout << "Sorted runs for Team A: ";
    for (int r : runs) std::cout << r << " ";
    std::cout << "\n";

    // BST example: insert runs
    BST<int> bst;
    for (int r : runs) bst.insert(r);
    std::vector<int> sorted = bst.inorderTraversal();
    std::cout << "BST inorder: ";
    for (int r : sorted) std::cout << r << " ";
    std::cout << "\n";

    // Hash Table example
    HashTable ht(10);
    ht.insert("Player A1");
    std::cout << "Player A1 in hash: " << ht.search("Player A1") << "\n";

    // Match Result
    std::cout << "\nMatch Result:\n";
    if (team1.totalRuns > team2.totalRuns) {
        std::cout << team1.name << " wins by " << (team1.totalRuns - team2.totalRuns) << " runs.\n";
    } else if (team2.totalRuns > team1.totalRuns) {
        std::cout << team2.name << " wins by " << (team2.totalRuns - team1.totalRuns) << " runs.\n";
    } else {
        std::cout << "Match drawn.\n";
    }

    // Top Batsman
    int maxRuns = 0;
    std::string topBatsman;
    for (int i = 0; i < 11; i++) {
        if (team1.players.get(i).runs > maxRuns) {
            maxRuns = team1.players.get(i).runs;
            topBatsman = team1.players.get(i).name;
        }
        if (team2.players.get(i).runs > maxRuns) {
            maxRuns = team2.players.get(i).runs;
            topBatsman = team2.players.get(i).name;
        }
    }
    std::cout << "Top Batsman: " << topBatsman << " with " << maxRuns << " runs.\n";

    // Top Bowler
    int maxWickets = 0;
    std::string topBowler;
    for (int i = 0; i < 11; i++) {
        if (team1.players.get(i).wickets_taken > maxWickets) {
            maxWickets = team1.players.get(i).wickets_taken;
            topBowler = team1.players.get(i).name;
        }
        if (team2.players.get(i).wickets_taken > maxWickets) {
            maxWickets = team2.players.get(i).wickets_taken;
            topBowler = team2.players.get(i).name;
        }
    }
    std::cout << "Top Bowler: " << topBowler << " with " << maxWickets << " wickets.\n";

    return 0;
}
